set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} -add [get_ports clk]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports reset]
set_property PULLDOWN true [get_ports reset]

set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports edit_mode]
set_property PULLDOWN true [get_ports edit_mode]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports up_ctrl]
set_property PULLDOWN true [get_ports up_ctrl]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports down_ctrl]
set_property PULLDOWN true [get_ports down_ctrl]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports right_ctrl]
set_property PULLDOWN true [get_ports right_ctrl]
set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS33} [get_ports left_ctrl]
set_property PULLDOWN true [get_ports left_ctrl]

set_property PACKAGE_PIN M21 [get_ports {hdmi_tx_p[0]}]
set_property PACKAGE_PIN L21 [get_ports {hdmi_tx_p[1]}]
set_property PACKAGE_PIN J21 [get_ports {hdmi_tx_p[2]}]
set_property PACKAGE_PIN N19 [get_ports hdmi_clk_p]
